#!/usr/bin/env bash
set -euo pipefail

STEAM_LIB="/mnt/data4/SteamLibrary/steamapps"
COMPAT_DIR="$HOME/.proton-compat"
NIX_FILE="$(dirname "$0")/proton-compat-mounts.nix"

declare -A games

for manifest in "$STEAM_LIB"/appmanifest_*.acf; do
    [ -f "$manifest" ] || continue
    appid=$(grep -oP '"appid"\s+"\K[0-9]+' "$manifest")
    name=$(grep -oP '"name"\s+"\K[^"]+' "$manifest")
    games[$appid]="$name"
done

if [ ${#games[@]} -eq 0 ]; then
    echo "No games found in $STEAM_LIB"
    exit 1
fi

# Create local compatdata dirs
for appid in "${!games[@]}"; do
    mkdir -p "$COMPAT_DIR/$appid"
done

# Generate nix file
{
    cat <<'HEADER'
{ ... }:

# Auto-generated by sync-proton-mounts.sh
# Bind-mount Proton compatdata from ext4 over exFAT so Wine prefixes
# get proper symlink and permission support.

let
  mkCompatMount = appId: {
    name = "/mnt/data4/SteamLibrary/steamapps/compatdata/${appId}";
    value = {
      device = "/home/alpineq/.proton-compat/${appId}";
      fsType = "none";
      options = [ "bind" "nofail" ];
    };
  };

  appIds = [
HEADER

    # Sort by app ID for stable output
    for appid in $(echo "${!games[@]}" | tr ' ' '\n' | sort -n); do
        printf '    "%-10s # %s\n' "${appid}\"" "${games[$appid]}"
    done

    cat <<'FOOTER'
  ];
in
{
  fileSystems = builtins.listToAttrs (map mkCompatMount appIds);
}
FOOTER
} > "$NIX_FILE"

echo "Updated $NIX_FILE with ${#games[@]} games:"
for appid in $(echo "${!games[@]}" | tr ' ' '\n' | sort -n); do
    echo "  $appid  ${games[$appid]}"
done
